---
name: New Helm Deployment
description: Configures a new service to deploy through helm
title: "[HELM]: "
labels: ["helm", "harness", "onboarding"]
# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - octocat
# type: bug
body:
  - type: markdown
    attributes:
      value: |
        This will create a new harness pipeline for a simple helm deployment!
  - type: input
    id: repository_name
    attributes:
      label: Repo Name
      description: The url to your tooling repository in lbg-cloud-platform
      placeholder: e.g. github.com/lbg-cloud-platform/359756-pexc-clenbl-tooling.git
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ## App Information
  - type: input
    id: chart_name
    attributes:
      label: Chart Name
      description: The name of the chart to deploy
    validations:
      required: true
  
  - type: input
    id: chart_name
    attributes:
      label: Chart Name
      description: The name of the chart to deploy
    validations:
      required: true
---