---
name: New Helm Deployment
description: Configures a new service to deploy through helm
title: "[HELM]: "
labels: ["helm", "harness", "onboarding"]
# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - octocat
# type: bug
body:
  - type: markdown
    attributes:
      value: |
        This will create a new harness pipeline for a simple helm deployment!
  - type: input
    id: tooling_repository_url
    attributes:
      label: Tooling Repo Url
      description: The url to your tooling repository in lbg-cloud-platform
      placeholder: github.com/lbg-cloud-platform/359756-pexc-clenbl-tooling.git
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ## App Information
  - type: input
    id: chart_name
    attributes:
      label: Chart Name
      description: The name of the chart to deploy
    validations:
      required: true
  - type: input
    id: namespace
    attributes:
      label: Namespace
      description: The namespace your app should deploy into
      placeholder: ns-kcl-tnt01-pppmsa-enablers-ext-apps
    validations:
      required: true
  - type: input
    id: repository
    attributes:
      label: Application Repo
      description: The repo where the application lives
      placeholder: tnt01-pppmsa-mock-external-service
    validations:
      required: true
---